"""Add QR system models

Revision ID: bd7ca04a74d3
Revises: 9deea113f2f9
Create Date: 2025-03-30 15:20:25.642834

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bd7ca04a74d3'
down_revision = '9deea113f2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
